# Generated by Django 3.2.6 on 2021-12-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_place',
            name='updated',
        ),
        migrations.AlterField(
            model_name='order_place',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
